### ISSUE TITLE
link to Annotator example file broken

### ISSUE THREAD

**Issue by tmontana** [OpenBioLink/ThoughtSource#113]
Hello.  The example file link on main readme page is broken:  https://github.com/OpenBioLink/ThoughtSource/blob/main/notebooks/worldtree_10.json

In addition, loading that file (worldtree_10.json) found elsewhere on the repo into the online Annotator demo generates an error (file not in correct format).  Thanks,

**Comment by matthias-samwald** [comment]
Thanks, we will look into it!

**Comment by KonstantinHebenstreit** [comment]
Hey! Thanks for the feedback. We could not reproduce the problem though...
Could you send screenshots of what is not working? 

What might have not worked when you tried:
1) Opening the file in the right format.
![image](https://user-images.githubusercontent.com/57603012/221817173-16c72e86-80f9-43c3-b500-66c4df0cbd81.png)
To do that you have to click raw.

2) When you opened it in raw format.
Save the file by right clicking on it and "Save page as"
On windows a json is then downloaded. 
![image](https://user-images.githubusercontent.com/57603012/221818044-4efe06a5-c36c-4265-a4c5-03ee78c4ff80.png)
If you are on another system, you might have to change the ending of the file to make it a json file. 

That should work. If not, don't hesitate to write another message with screenshots or more detailed explanation what does not work :)

**Comment by tmontana** [comment]
Hi - it's all working again.  Not sure why the link to the file appeared broken when I first tried it.  Indeed the file format issue was due to not saving the file as raw.  I just right clicked and saved link as but that's wrong.  The right approach is the one you suggest.  Many thanks for looking into it.  Cheers

**Comment by KonstantinHebenstreit** [comment]
You are welcome :)
