### ISSUE TITLE
Tutorial notebook does not open

### ISSUE THREAD

**Issue by TolgaCorbaci** [OpenBioLink/ThoughtSource#128]
I get the following error:
Invalid Notebook
Additional properties are not allowed ('id' was unexpected)
Using nbformat v5.8.0 and nbconvert v7.2.7

**Comment by KonstantinHebenstreit** [comment]
I do not think that is an error from our side...
It seems that some cells in the notebook have the same ids, which results from copying a cell within a notebook. And nbformat does not accept that at the moment.
