### ISSUE TITLE
Dataset: AQuA

### ISSUE THREAD

**Issue by nomisto** [OpenBioLink/ThoughtSource#18]
Homepage: https://github.com/deepmind/AQuA
Example:
```json
{
"question": "A grocery sells a bag of ice for $1.25, and makes 20% profit. If it sells 500 bags of ice, how much total profit does it make?",
"options": ["A)125", "B)150", "C)225", "D)250", "E)275"],
"rationale": "Profit per bag = 1.25 * 0.20 = 0.25\nTotal profit = 500 * 0.25 = 125\nAnswer is A.",
"correct": "A"
}
```

**Comment by matthias-samwald** [comment]
The CoT reference answers with A, B, C etc, but we do not have them explicitly in the dataset anymore. But I guess we can standardize to using A, B, C etc for referring to choices with array index 0, 1, 2 etc. Is this already done consistently across datasets?

![Image](https://user-images.githubusercontent.com/6213601/180979962-5a367053-4f4c-4a9d-95b2-0cc73d43b2e5.png)

**Comment by nomisto** [comment]
Ah, I would remove "Answer : B" completely then, to be consistent with other datasets (No other dataset has the answer in the cot and I would delegate this to prompting then.)

**Comment by matthias-samwald** [comment]
A general observation on the current state of AQuA: The style and formatting of the CoTs and the final answers in the CoTs is __quite__ noisy; there is also a substantial amount of spelling mistakes and ad-hoc abreviations.

**Comment by matthias-samwald** [comment]
> Ah, I would remove "Answer : B" completely then, to be consistent with other datasets (No other dataset has the answer in the cot and I would delegate this to prompting then.)

Okay!

**Comment by nomisto** [comment]
As said data is quite noisy, so filtering the answer does not really work in a clean way. I'd use the standardized references as you said.

**Comment by matthias-samwald** [comment]
From personal communication with Simon: The datasets refers to A, B, C etc also in other parts of the CoT stream, not only in the final answer, so it would be difficult to remove these references entirely.

I agree that we should standardize on A, B, C schema for multiple choice, which conveniently means that we don't have to do anything for this dataset  :)

**Comment by KonstantinHebenstreit** [comment]
Error in Aqua dataset (validation set, id: 0)
"question":"Three birds are flying at a fast rate of 900 kilometers per hour. What is their speed in miles per minute? [1km = 0.6 miles]"
"rationale":"To calculate the equivalent of miles in a kilometer 0.6 kilometers = 1 mile 900 kilometers = (0.6)*900 = 540 miles In 1 hour there are 60 minutes Speed in miles/minutes = 60 * 540 = 32400 Correct answer - A"
"answer":"32400"

Error: Multiplied instead of divided.
