### ISSUE TITLE
Dataset: CommonsenseQA

### ISSUE THREAD

**Issue by nomisto** [OpenBioLink/ThoughtSource#19]
The [CommonsenseQA dataset](https://www.tau-nlp.sites.tau.ac.il/commonsenseqa) with CoTs derives from explanations from the [ECQA dataset](https://github.com/dair-iitd/ECQA-Dataset).

Potential todos for post-processing the dataset to improve quality:

- [ ] First letter in each CoT entry is not consistently capitalized, this could be fixed easily

![image](https://user-images.githubusercontent.com/6213601/181008506-24f978f3-8a3b-43c1-84f7-c62b1679a615.png)

- [ ] There is a substantial number of typos and grammatical errors that could be corrected. This is of course difficult given the vast size of the dataset. Maybe it could at least in part be done (semi-)automatically?

**Comment by matthias-samwald** [comment]
@nomisto "type" value should probably be "multiplechoice" instead of "number"

![Image](https://user-images.githubusercontent.com/6213601/180978839-c768cee4-a43f-4aac-8e6d-67c5acd07045.png)

**Comment by matthias-samwald** [comment]
@nomisto We need to clarify from which of the potential two explanation datasets the current CoTs were derived.

**Comment by nomisto** [comment]
The current explanations are from ECQA (I've written this in the README but I'll also include this in the description of the dataloader). cos-e explanations are a little weird, but we can look into including them.

**Comment by matthias-samwald** [comment]
I looked at cos-e and can see why the data are weird; let's just not include cos-e.

**Comment by nomisto** [comment]
Capitalization is easy, but for errors should we use something like https://huggingface.co/prithivida/grammar_error_correcter_v1?text=This+is+an+eror?

**Comment by nomisto** [comment]
One other thing is that we have to split the sentences by ourselves. Until now I did it with nltk sent_tokenizer, but this fails to split e.g the following CoT `'Math problem is an arithmetical problem of addition, subtraction, multiplication or division. So "There are 10 apples on an apple tree.  Three fall off.  Now there are X apples." is a math problem. All the other options aren\'t problems to be examples of the given question.'`

**Comment by matthias-samwald** [comment]
I think we should fix the capitalization for now, and leave everything else for future work.
