### ISSUE TITLE
Dataset: WorldTree

### ISSUE THREAD

**Issue by matthias-samwald** [OpenBioLink/ThoughtSource#5]

**Comment by matthias-samwald** [comment]
- [ ] First character in CoTs could be capitalized
- [ ] For some entities in CoTs, the datasets gives alternative terms / synomyns, like `roots are a part of a (plant ; tree)`. Not sure what to do with this, probably we could leave it so alternatives can be randomly picked during prompt generation? If we leave such cases in, we should however have a standardized syntax (e.g. Jinja, inspired by PromptSource)


![Image](https://user-images.githubusercontent.com/6213601/181022414-a4b321a1-4d54-48c8-94f3-b05b13202915.png)

**Comment by nomisto** [comment]
Hm the second point is not trivial. We would have to store the alternatives in a structured way (Add it to the schema) to convert them later to unstructured (with e.g. jinja). My first thought was again some kind of standardized reference?

Like f.e. include a field called "synsets": [["plant", "tree"], ....] in the schema and the sentence `roots are a part of a (plant ; tree)` would then change to `roots are a part of a #1` or something like that to reference the synset at index 0. 

With jinja you could then replace them again to form a sentence.

**Comment by matthias-samwald** [comment]
Hm, I'd advocate against expanding the schema right now for the sake of keeping it simple -- WorldTree is currently the only dataset where this is relevant. 
I suggest we pragmatically pick the first value of the alternatives each time, and remove the other synonyms.
